import streamlit as st
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

st.set_page_config(
    page_title="Age Detection Using CNN",
    page_icon="🎂"
)

st.title("🎂 Age Detection Using CNN")

st.write(
    "This application demonstrates a CNN model "
    "for age-group classification using synthetic images."
)

@st.cache_resource
def create_model():
    model = Sequential([
        Conv2D(
            32,
            (3, 3),
            activation="relu",
            input_shape=(64, 64, 3)
        ),
        MaxPooling2D((2, 2)),

        Conv2D(64, (3, 3), activation="relu"),
        MaxPooling2D((2, 2)),

        Flatten(),
        Dense(128, activation="relu"),
        Dropout(0.3),

        Dense(4, activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

model = create_model()

st.warning(
    "Demo only: This model is not trained on the "
    "IMDB-WIKI dataset and cannot reliably estimate age."
)

if st.button("Generate Demo Prediction"):

    # Generate a synthetic image
    image = np.random.rand(64, 64, 3).astype(np.float32)

    # Reshape image for CNN input
    image = image.reshape(1, 64, 64, 3)

    # Generate prediction
    prediction = model.predict(image, verbose=0)[0]

    age_groups = [
        "Child (0–17)",
        "Young Adult (18–35)",
        "Middle-Aged (36–60)",
        "Senior (61+)"
    ]

    predicted_class = np.argmax(prediction)

    st.write(
        "Demo Predicted Age Group:",
        age_groups[predicted_class]
    )

    st.write(
        "Demo Model Output:",
        float(prediction[predicted_class])
    )

    st.info(
        "This result is generated by an untrained model "
        "using a synthetic image. It is not a real age prediction."
    )
